/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-06-02 08:21:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.body;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<style>\r\n");
      out.write(".clsBannerScreen {overflow: hidden;position: relative;height: 150px;width: 600px; border:1px solid #e1e1e1; cursor:pointer; clear:both;}\r\n");
      out.write(".clsBannerScreen .images {position:absolute; display:none; }\r\n");
      out.write("ul, li {list-style:none; margin:0; padding:0; font-size:10pt; }\r\n");
      out.write(".clsBannerButton {width:600px;cursor:pointer;border-bottom:1px solid #e1e1e1;}\r\n");
      out.write(".clsBannerButton li {width:100px;float:left;border-right:1px solid #e1e1e1;padding:2px;}\r\n");
      out.write(".clsBannerButton li.fir {border-left:1px solid #e1e1e1;}\r\n");
      out.write("\r\n");
      out.write(".clsBannerButton li.labelOverClass {font-weight:bold;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/script/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/script/jquery.banner.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$.ajax(){\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("$(function() {\r\n");
      out.write("\t$(\"#image_list_1\").jQBanner({\t//롤링을 할 영역의 ID 값\r\n");
      out.write("\t\tnWidth:600,\t\t\t\t\t//영역의 width\r\n");
      out.write("\t\tnHeight:150,\t\t\t\t//영역의 height\r\n");
      out.write("\t\tnCount:5,\t\t\t\t\t//돌아갈 이미지 개수\r\n");
      out.write("\t\tisActType:\"up\",\t\t\t\t//움직일 방향 (left, right, up, down)\r\n");
      out.write("\t\tnOrderNo:1,\t\t\t\t\t//초기 이미지\r\n");
      out.write("\t\tnDelay:2000\t\t\t\t\t//롤링 시간 타임 (1000 = 1초)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t);\r\n");
      out.write("});\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"image_list_1\">\r\n");
      out.write("<ul class=\"clsBannerButton\" id=\"label_1\">\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/1on.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/1on.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/1.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/2.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/2.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/2.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/3.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/3.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/3.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/4.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/4.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/4.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/5.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/5.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/5.png\" /></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<div class=\"clsBannerScreen\">\r\n");
      out.write("\t<div class=\"images\" style=\"display:block\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/google.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/daum.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/naver.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/nate.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/yahoo.jpg\" /></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"image_list_2\">\r\n");
      out.write("<ul class=\"clsBannerButton\" id=\"label_2\">\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/1on.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/1on.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/1.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/2.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/2.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/2.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/3.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/3.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/3.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/4.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/4.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/4.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/5.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/5.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/5.png\" /></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("<div class=\"clsBannerScreen\">\r\n");
      out.write("\t<div class=\"images\" style=\"display:block\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/google.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/daum.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/naver.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/nate.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/yahoo.jpg\" /></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"image_list_3\">\r\n");
      out.write("<ul class=\"clsBannerButton\" id=\"label_3\">\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/1on.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/1on.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/1.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/2.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/2.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/2.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/3.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/3.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/3.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/4.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/4.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/4.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/5.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/5.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/5.png\" /></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<div class=\"clsBannerScreen\">\r\n");
      out.write("\t<div class=\"images\" style=\"display:block\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/google.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/daum.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/naver.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/nate.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/yahoo.jpg\" /></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"image_list_4\">\r\n");
      out.write("<ul class=\"clsBannerButton\" id=\"label_4\">\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/1on.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/1on.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/1.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/2.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/2.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/2.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/3.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/3.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/3.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/4.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/4.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/4.png\" /></li>\r\n");
      out.write("\t<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/5.png\" onmouseover=\"");
      out.print(request.getContextPath());
      out.write("/image/5.png\" onmouseout=\"");
      out.print(request.getContextPath());
      out.write("/image/5.png\" /></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("<div class=\"clsBannerScreen\">\r\n");
      out.write("\t<div class=\"images\" style=\"display:block\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/google.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/daum.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/naver.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/nate.jpg\" /></div>\r\n");
      out.write("\t<div class=\"images\"><img src=\"http://cfs.tistory.com/custom/blog/68/684698/skin/images/yahoo.jpg\" /></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
