/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-29 06:37:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.body.buyer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class buyer_005flogin_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/buyer.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/script/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t//바이어 와 셀러의 로그인 화면 변경\r\n");
      out.write("\t$(\".login\").on(\"click\", function() {\r\n");
      out.write("\t\t\tif ($(this).attr(\"id\") == 'bLogin') {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#slog\").hide();\r\n");
      out.write("\t\t\t\t$(\"#blog\").show();\r\n");
      out.write("\t\t\t\t$(\"#sId\").val('');\r\n");
      out.write("\t\t\t\t$(\"#sPassword\").val('');\r\n");
      out.write("\r\n");
      out.write("\t\t\t} else if ($(this).attr(\"id\") == 'sLogin') {\r\n");
      out.write("\t\t\t\t$(\"#blog\").hide();\r\n");
      out.write("\t\t\t\t$(\"#slog\").show();\r\n");
      out.write("\t\t\t\t$(\"#bId\").val('');\r\n");
      out.write("\t\t\t\t$(\"#bPassword\").val('');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t$(\"#sButton\").on(\"click\",function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#sId\").val().trim()==''){\r\n");
      out.write("\t\t\t$(\"#sIdErr\").show();\r\n");
      out.write("\t\t\t$(\"#sPasswordErr\").hide();\r\n");
      out.write("\t\t\t$(\"#sId\").val('');\r\n");
      out.write("\t\t\t$(\"#sId\").focus();\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#sPassword\").val().trim()==''){\r\n");
      out.write("\t\t\t$(\"#sIdErr\").hide();\r\n");
      out.write("\t\t\t$(\"#sPasswordErr\").show();\r\n");
      out.write("\t\t\t$(\"#sPassword\").val('');\r\n");
      out.write("\t\t\t$(\"#sPassword\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t//셀러 로그인 처리\r\n");
      out.write("\t\t$(\"#bButton\").on(\"click\",function(){\r\n");
      out.write("\t\t\talert('dd');\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/taommall/buyer/buyerLogin.do\",\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\tdata:{bId:$(\"#bId\").val(),bPassword:$(\"#bPassword\").val()},\t\r\n");
      out.write("\t\t\t\tdataType:\"text\",\r\n");
      out.write("\t\t\t\tbeforeSend:function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t//바이어 로그인 처리\r\n");
      out.write("\t\t\t\t\t\tif($(\"#bId\").val().trim()==''){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#bIdErr\").show();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#bPasswordErr\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#bId\").val('');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#bId\").focus();\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif($(\"#bPassword\").val().trim()==''){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#bIdErr\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#bPasswordErr\").show();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#bPassword\").val('');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#bPassword\").focus();\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess:function(res){\r\n");
      out.write("\t\t\t\t\talert('성공?');\r\n");
      out.write("\t\t\t\t\talert(res);\r\n");
      out.write("\t\t\t\t\tif(res=='success'){\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"buyerLogin\").submit();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert('dd');\r\n");
      out.write("\t\t\t\t\t\t$(\"#bLoginError\").show();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//셀러 로그인 처리\r\n");
      out.write("\t\t$(\"#sButton\").on(\"click\",function(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/taommall/seller/sellerLogin.do\",\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\tdata:{sId:$(\"#sId\").val(),sPassword:$(\"#sPassword\").val()},\t\r\n");
      out.write("\t\t\t\tdataType:\"text\",\r\n");
      out.write("\t\t\t\tbeforeSend:function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t//바이어 로그인 처리\r\n");
      out.write("\t\t\t\t\t\tif($(\"#sId\").val().trim()==''){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#sIdErr\").show();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#sPasswordErr\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#sId\").val('');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#sId\").focus();\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif($(\"#sPassword\").val().trim()==''){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#sIdErr\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#sPasswordErr\").show();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#sPassword\").val('');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#sPassword\").focus();\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess:function(res){\r\n");
      out.write("\t\t\t\t\talert('성공?');\r\n");
      out.write("\t\t\t\t\talert(res);\r\n");
      out.write("\t\t\t\t\tif(res=='success'){\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"sellerLogin\").submit();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert('dd');\r\n");
      out.write("\t\t\t\t\t\t$(\"#sLoginError\").show();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("\t<label>바이어<input type=\"radio\" id=\"bLogin\"  name=\"login\" class=\"login\" checked=\"checked\"></label>\r\n");
      out.write("\t<label>셀러<input type=\"radio\" id=\"sLogin\" name=\"login\" class=\"login\" ></label>\r\n");
      out.write("\t<fieldset style=\"height:200px;border:none;\">\r\n");
      out.write("\t<div\t id=\"blog\" class=\"loginForm\">\r\n");
      out.write("\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/buyer/buyerInfoForm.do\" class=\"loginForm\" id=\"buyerLogin\" method=\"post\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<input type=\"text\" name=\"bId\" id=\"bId\" placeholder=\"아이디1\" class=\"loginInput\">\r\n");
      out.write("\t\t<span id=\"bIdErr\" class=\"error\" style=\"display:none\">아이디를 입력해주세요.</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<input type=\"text\" name=\"bPassword\" id=\"bPassword\" placeholder=\"비밀번호\"class=\"loginInput\">\r\n");
      out.write("\t\t<span id=\"bPasswordErr\" class=\"error\" style=\"display:none\">비밀번호를 입력해주세요.</span> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<span id=\"bLoginError\" class=\"error\" style=\"display:none\">아이디 또는 비밀번호를 다시 확인하세요.<br> 등록되지 않은 아이디이거나, 아이디 또는 비밀번호를 잘못 입력하셨습니다.<br></span> \r\n");
      out.write("\t\t<input type=\"button\" id=\"bButton\" value=\"전송\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"slog\" class=\"loginForm\" style=\"display:none\">\r\n");
      out.write("\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/seller/sellerInfoForm.do\" class=\"loginForm\" id=\"sellerLogin\" method=\"post\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<input type=\"text\" name=\"sId\" id=\"sId\" placeholder=\"아이디2\" class=\"loginInput\">\r\n");
      out.write("\t\t<span id=\"sIdErr\" class=\"error\" style=\"display:none\">아이디를 입력해주세요.</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<input type=\"text\" name=\"sPassword\" id=\"sPassword\" placeholder=\"비밀번호\"class=\"loginInput\">\r\n");
      out.write("\t\t<span id=\"sPasswordErr\" class=\"error\" style=\"display:none\">비밀번호를 입력해주세요.</span> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<span id=\"sLoginError\" class=\"error\" style=\"display:none\">아이디 또는 비밀번호를 다시 확인하세요.<br> 등록되지 않은 아이디이거나, 아이디 또는 비밀번호를 잘못 입력하셨습니다.<br></span>\r\n");
      out.write("\t\t<input type=\"button\" id=\"sButton\" value=\"전송\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
